'use server';

import { prisma } from '@/lib/db';
import archiver from 'archiver';
import { Readable } from 'stream';

// Helper to buffer the stream
const _streamToBuffer = (stream: Readable): Promise<Buffer> => {
  return new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];
    stream.on('data', (chunk: Buffer) => chunks.push(chunk));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);
  });
};

export async function exportLandingPageZip(variantId: string) {
  try {
    const variant = await prisma.landingPageVariant.findUnique({
      where: { id: variantId },
      include: { project: true },
    });
    if (!variant || !variant.pageJson) throw new Error('Variant not found or empty');

    const archive = archiver('zip', { zlib: { level: 9 } });
    const chunks: any[] = [];
    
    // We'll use a Promise wrapper to capture data
    const promise = new Promise<Buffer>((resolve, reject) => {
      archive.on('data', (data) => chunks.push(data));
      archive.on('end', () => resolve(Buffer.concat(chunks)));
      archive.on('error', reject);
    });

    // Generate HTML content
    const html = generateStaticHtml(variant.pageJson, variant.project.idea); // Basic idea name as fallback title
    
    archive.append(html, { name: 'index.html' });
    
    const readme = `
# Landing Page Export

This folder contains your static landing page.

1. Upload contents to any static host (Netlify, Vercel, GitHub Pages, S3).
2. The form is configured to POST to: [YOUR_APP_URL]/p/${variant.slug || 'slug'}/lead (or api endpoint).
   - If hosting strictly statically without this app running, you must change the form action or use a service like Formspree.

Generated by CookAI.
    `;
    archive.append(readme, { name: 'README.md' });

    // Finalize
    archive.finalize();
    const buffer = await promise;

    return { 
      success: true, 
      data: buffer.toString('base64'), 
      filename: `landing-page-${variant.slug || variant.version}.zip` 
    };

  } catch (error) {
    console.error('Export failed', error);
    return { success: false, error: String(error) };
  }
}

function generateStaticHtml(pageJson: any, titleInfo: string) {
  const p = pageJson as any;
  const sections = p.sections || {};
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${p.theme?.brandName || titleInfo}</title>
    <style>
        body { font-family: system-ui, sans-serif; line-height: 1.5; margin: 0; color: #1f2937; }
        .container { max-width: 1024px; margin: 0 auto; padding: 2rem; }
        .btn { display: inline-block; padding: 0.75rem 1.5rem; background: #2563eb; color: white; text-decoration: none; border-radius: 0.375rem; border: none; cursor: pointer; }
        .section { padding: 4rem 1rem; }
        .hero { background: #f3f4f6; text-align: center; }
        .hero h1 { font-size: 3rem; margin-bottom: 1rem; }
        .grid { display: grid; gap: 2rem; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); }
        .card { border: 1px solid #e5e7eb; padding: 1.5rem; border-radius: 0.5rem; }
        form { display: flex; flex-direction: column; gap: 1rem; max-width: 400px; margin: 0 auto; }
        input, textarea { padding: 0.5rem; border: 1px solid #d1d5db; border-radius: 0.25rem; }
    </style>
</head>
<body>

    <div class="section hero">
        <div class="container">
            <h1>${sections.hero?.headline || ''}</h1>
            <p style="font-size: 1.25rem; color: #4b5563;">${sections.hero?.subheadline || ''}</p>
            <div style="margin-top: 2rem;">
                <a href="#offer" class="btn">${sections.hero?.ctaText || 'Get Started'}</a>
            </div>
            ${sections.hero?.bulletBenefits ? `
            <ul style="list-style: none; padding: 0; margin-top: 2rem; display: flex; gap: 1rem; justify-content: center;">
                ${sections.hero.bulletBenefits.map((b: string) => `<li>✓ ${b}</li>`).join('')}
            </ul>
            ` : ''}
        </div>
    </div>

    <div class="section" id="lead-form">
        <div class="container" style="text-align: center;">
            <h2>${sections.leadForm?.headline || 'Contact Us'}</h2>
            <p>${sections.leadForm?.subheadline || ''}</p>
            
            <form action="YOUR_ENDPOINT_HERE" method="POST">
                <input type="text" name="name" placeholder="Name" required>
                <input type="email" name="email" placeholder="Email" required>
                ${sections.leadForm?.fieldsEnabled?.phone ? '<input type="tel" name="phone" placeholder="Phone">' : ''}
                ${sections.leadForm?.fieldsEnabled?.message ? '<textarea name="message" placeholder="Message"></textarea>' : ''}
                <input type="hidden" name="_hp" value="">
                
                <button type="submit" class="btn">Submit</button>
            </form>
        </div>
    </div>

    <footer class="section" style="background: #111827; color: white;">
        <div class="container">
            <p>${sections.footer?.disclaimerText || ''}</p>
        </div>
    </footer>

</body>
</html>
  `;
}
