import { LLMClient } from '../../llm/types';
import { ResearchInput, ResearchProvider, ResearchResult } from './types';
import { ResearchReportSchema } from './schemas';

export class LLMResearchProvider implements ResearchProvider {
  private client: LLMClient;

  constructor(client: LLMClient) {
    this.client = client;
  }

  async generate(input: ResearchInput): Promise<ResearchResult> {
    const prompt = `
      Analyze the market for the following project idea:
      
      Project: ${input.idea}
      Target Market: ${input.targetMarket}
      Revenue Goal: ${input.revenueGoal}
      Brand Voice: ${input.brandVoiceBrief}
      
      Generate a comprehensive market research report including:
      1. Executive Summary
      2. Ideal Customer Profile (ICP)
      3. Market Analysis (TAM/SAM/SOM estimates)
      4. Competitor Analysis (Hypothetical or real if known)
      5. Opportunities & Marketing Angles
    `;

    const systemPrompt = "You are a world-class market research analyst. Provide specific, data-backed (or realistic estimates) insights. Output strictly valid JSON.";

    const content = await this.client.generateJson(
      prompt,
      ResearchReportSchema,
      'ResearchReport',
      systemPrompt
    );

    // LLM doesn't easily generate real verifyable sources without browsing. 
    // We will simulate generic "Search Queries" as sources or omit them.
    const sources = [
      { title: 'Market Analysis Logic', url: 'Generated by AI based on market patterns' }
    ];

    return {
      content,
      sources
    };
  }
}
