import { prisma } from "@/lib/db";
import { notFound } from "next/navigation";

// Force dynamic to ensure fresh data for exports
export const dynamic = 'force-dynamic';

export default async function ProjectExportView({ params }: { params: Promise<{ id: string }> }) {
  // Await params as per Next.js 15+ requirements if applicable, or safe to await in recent versions
  const { id } = await params;
  
  const project = await prisma.project.findUnique({
    where: { id },
    include: {
      researchReports: {
        where: { status: 'FINAL' },
        orderBy: { version: 'desc' },
        take: 1
      },
      offers: {
        where: { status: 'FINAL' },
        orderBy: { version: 'desc' },
        take: 1
      },
      assetBundles: {
        where: { status: 'FINAL' },
        orderBy: { version: 'desc' },
        take: 1
      }
    }
  });

  if (!project) notFound();

  const report = project.researchReports[0];
  const offer = project.offers[0];
  // const assets = project.assetBundles[0]; // Not typically in the PDF business plan unless summarized

  return (
    <div className="max-w-4xl mx-auto p-12 bg-white text-black print:p-0">
      {/* Cover Page */}
      <div className="min-h-[1000px] flex flex-col justify-center items-center text-center border-b-2 border-gray-100 mb-12 break-after-page">
        <h1 className="text-5xl font-bold mb-6">{project.idea}</h1>
        <p className="text-xl text-gray-600 mb-4">Business Plan & Strategy</p>
        <p className="text-sm text-gray-400">Generated on {new Date().toLocaleDateString()}</p>
      </div>

      {/* Executive Summary / Research */}
      <section className="mb-12 page-break-inside-avoid">
        <h2 className="text-2xl font-bold border-b-2 border-black pb-2 mb-6">Market Research</h2>
        {report?.content ? (
          <div className="prose prose-sm max-w-none">
             {/* Note: In a real app, we might need a markdown renderer here. 
                 For now, we assume simple text or dumping the JSON structure 
                 if it's not pre-processed. JSON.stringify for safety if structure unknown. */}
             <pre className="whitespace-pre-wrap font-sans text-sm">
               {JSON.stringify(report.content, null, 2)}
             </pre>
          </div>
        ) : (
          <div className="p-4 bg-gray-50 border border-gray-200 rounded">
            No finalized research report found.
          </div>
        )}
      </section>

      {/* Offer Strategy */}
      <section className="mb-12 break-inside-avoid">
        <h2 className="text-2xl font-bold border-b-2 border-black pb-2 mb-6">Offer Strategy</h2>
        {offer ? (
           <div className="prose prose-sm max-w-none">
             <div className="mb-4">
               <h3 className="font-bold">Guarantee</h3>
               <p>{offer.guarantee || "N/A"}</p>
             </div>
             <div>
               <h3 className="font-bold">Rationale</h3>
               <p>{offer.rationale || "N/A"}</p>
             </div>
             {/* Add Tiers rendering if structure known */}
           </div>
        ) : (
          <div className="p-4 bg-gray-50 border border-gray-200 rounded">
            No finalized offer strategy found.
          </div>
        )}
      </section>
      
      {/* Footer */}
      <div className="text-center text-xs text-gray-400 mt-20 pt-10 border-t">
        Generated by CookAI Clone (Local Version)
      </div>

    </div>
  );
}
